server {
    listen 80;
    server_name www.aitherios.cloud;
    return 301 $scheme://aitherios.cloud$request_uri;
}

server {
    listen 80;
    server_name aitherios.cloud;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
