# Generated by Django 6.0.3 on 2026-03-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_safetycard'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentationcard',
            name='shipping_night_shift',
            field=models.CharField(default='4:30PM - 1:00AM', max_length=100),
        ),
    ]
