# Generated by Django 6.0.3 on 2026-03-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_presentationcard_shipping_night_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(default='AMJK', max_length=50)),
                ('product_group', models.CharField(default='SW', max_length=50)),
                ('carrier_percentages', models.JSONField(default=dict)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_synced'],
            },
        ),
        migrations.CreateModel(
            name='FreightAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(default='AMJK', max_length=50)),
                ('product_group', models.CharField(default='SW', max_length=50)),
                ('hist_avg_frt_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hist_avg_ttl_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('hist_avg_cost_per_lb', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('ytd_frt_amt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ytd_ttl_lbs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ytd_cost_per_lb', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('frt_amt_delta_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lbs_delta_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cost_per_lb_delta_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_synced'],
            },
        ),
    ]
